name: GitHub Actions Demo
on: 
  push:
    branches: [ main ]
    paths-ignore: [.github/**]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "15 6 * * 0"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment we want to deploy to"
        type: environment
        required: true

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: "Echo Test 1"
        run: echo "The job was triggered by the following event ${{ github.event_name }}"
        
      - name: "Echo Test 2"
        run: "echo \"The job was triggered by the following event: ${{ github.event_name }}\""
          
      - name: "Echo details"
        run: |
          echo "The job was triggered by the following event: ${{ github.event_name }}"
          echo "The name of your branch is ${{ github.ref }}."

      - uses: actions/checkout@v3.3.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
  Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch' & github.event.inputs.environment == 'Test'
    environment: Test
    steps:
      - name: "Run test environment"
        run: echo "Testing..."

  Load-Test:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event_name == 'workflow_dispatch' & github.event.inputs.environment == 'Load-Test'
    environment: Load-Test
    steps:
      - name: "Run test environment"
        run: | 
          echo "Testing..."
          sleep 15

  Production:
    runs-on: ubuntu-latest
    needs: 
      - Test
      - Load-Test
    environment: 
      name: Production
      url: https://writeabout.net
    if: github.event.inputs.environment == 'Production'
    steps:
      - name: Step 1
        run: |
          echo "Deploying..."
          sleep 10
      - name: Step 2
        run: |
          echo "Deploying..."
          sleep 10
      - name: Step 3
        run: |
          echo "Deploying..."
          sleep 10
      - name: Step 4
        run: |
          echo "Deploying..."
          sleep 10
      - name: Step 5
        run: |
          echo "Deploying..."
          sleep 10
      - name: Complete
        run: |
          echo "Complete."
    
